version: 1.0.{build}
image: Visual Studio 2022
configuration: Release
platform: Any CPU
before_build:
- ps: nuget restore
build:
  verbosity: minimal
after_build:
- ps: 7z a WaypointCreatorGen2.zip $Env:APPVEYOR_BUILD_FOLDER"\WaypointCreatorGen2\bin\Release\*"
artifacts:
- path: WaypointCreatorGen2.zip
